### PR TITLE
FE-76 Populate resources page

### PR DESCRIPTION
**Pull request by durbster**

### CODE REVIEW

**Comment by durbster** [comment]
Just closed this to make some improvements.

**Comment by mike-f50** [comment]
Hi @durbster .  Sorry, there are now some conflicts here if you wouldn't mind taking a look.

**Comment by jamesbloor** [comment]
@mike-f50 @durbster I've resolved these conflicts for you (I caused the conflict...)

**Comment by durbster** [comment]
Just sorting this out now.

**Comment by durbster** [comment]
All looks good but I can't approve as it's my PR!

**Pull request merged**
