### PR TITLE
Fixed the button getting cut up on mobile

### PR DESCRIPTION
**Pull request by daisymaclennan**

### CODE REVIEW

**Comment by daisymaclennan** [comment]
Yeah, can you make sure your moving tasks over to in progress because it was in ready for development

**Comment by durbster** [comment]
> Yeah, can you make sure your moving tasks over to in progress because it was in ready for development

Yep, sorry. I assigned it to myself but didn't update the status.

**Comment by durbster** [comment]
Looks like there's no overlap actually so I can merge your change into my branch.

**Comment by durbster** [comment]
Closing this as these changes are merged with #48

**Pull request closed without merging**
